### ISSUE TITLE
Update mime version (and publish)

### ISSUE THREAD

**Issue by mblarsen** [faceleg/node-s3-client#3]
See https://github.com/andrewrk/node-s3-client/pull/147#issuecomment-282584149

**Comment by faceleg** [comment]
I don't use this module. I'm willing to merge/publish but I'm not getting a PR ready etc for it.

Anyone who wants this merged please open a PR on this repo.

**Comment by mblarsen** [comment]
How come you are handling the NPM when the other is the main repo, just curious? Wouldn't it make more sense to let @andrewk handle that?

**Comment by faceleg** [comment]
It totally would make more sense. He seems to have become unresponsive - I have collaborator rights to that repo but not to the npm module ...

**Comment by mblarsen** [comment]
So who has the publishing rights?

**Comment by andrewk** [comment]
You've pinged the wrong account, I expect you meant @andrewrk

**Comment by faceleg** [comment]
@mblarsen @andrewrk does. I have rights for this repo's npm module
